### ISSUE TITLE
can't build with swift4.1

### ISSUE THREAD

**Issue by qiushuitian** [delba/TextAttributes#27]
install with the lib using pod . The version is 1.0. And can't build with newest swift version( swift 4.1).
```
Using TextAttributes (1.0)
```

**Comment by Samrat555** [comment]
Same issue happens. Please update it to swift 4.1

**Comment by annjose** [comment]
I have submitted a PR https://github.com/delba/TextAttributes/pull/28 that adds Swift 4 support.  It has migrated all the source code and all project targets (iOS, MacOS, watch and tvOS) to Swift 4.

@delba : Could add the label `hacktoberfest` to this issue so that this would qualify for the [Hacktoberfest contest](https://hacktoberfest.digitalocean.com/) and give some credits?

**Comment by markus-mohemian** [comment]
+1 to merge this one soon

**Comment by delba** [comment]
Hi @qiushuitian, the lib has been updated to the latest Swift version.
